-- Acompanhamentos do Açaí - Sorveteria Conteiner

-- Inserir acompanhamentos inclusos (gratuitos)
INSERT INTO produtos (nome, descricao, preco, categoria_id, bar_id, ativo) VALUES
-- Acompanhamentos Inclusos (gratuitos)
('Amendoim (Incluso)', 'Amendoim - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Banana (Incluso)', 'Banana - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Beijinho (Incluso)', 'Beijinho - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Brigadeiro (Incluso)', 'Brigadeiro - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Bis (Incluso)', 'Bis - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Calda Quente (Incluso)', 'Calda Quente - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Canudo wafer (Incluso)', 'Canudo wafer - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Chantilly (Incluso)', 'Chantilly - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Creme de avelã (Incluso)', 'Creme de avelã - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Chocoball (Incluso)', 'Chocoball - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Cobertura (Incluso)', 'Cobertura - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Confeti (Incluso)', 'Confeti - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Gotas de chocolate (Incluso)', 'Gotas de chocolate - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Granola (Incluso)', 'Granola - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Granulado (Incluso)', 'Granulado - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Groselha (Incluso)', 'Groselha - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Leite condensado (Incluso)', 'Leite condensado - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Leite em Pó (Incluso)', 'Leite em Pó - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Manga (Incluso)', 'Manga - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Marshmallow (Incluso)', 'Marshmallow - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Mel (Incluso)', 'Mel - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Negresco (Incluso)', 'Negresco - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Ovomaltine (Incluso)', 'Ovomaltine - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Ouro branco (Incluso)', 'Ouro branco - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Paçoquinha (Incluso)', 'Paçoquinha - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Sonho de valsa (Incluso)', 'Sonho de valsa - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Sucrilhos (Incluso)', 'Sucrilhos - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Suspiro (Incluso)', 'Suspiro - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Sorvete (Incluso)', 'Sorvete - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Uva (Incluso)', 'Uva - acompanhamento incluso no açaí', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),

-- Adicionais Extras (pagamento individual)
('Abacaxi ao vinho', 'Abacaxi ao vinho - adicional extra para açaí', 3.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Abacaxi em polpa', 'Abacaxi em polpa - adicional extra para açaí', 3.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Castanha de caju', 'Castanha de caju - adicional extra para açaí', 2.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Cereja', 'Cereja - adicional extra para açaí', 5.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Creme de morango', 'Creme de morango - adicional extra para açaí', 5.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Creme de bombom', 'Creme de bombom - adicional extra para açaí', 5.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Diamante negro', 'Diamante negro - adicional extra para açaí', 4.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Kiwi', 'Kiwi - adicional extra para açaí', 5.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Laka', 'Laka - adicional extra para açaí', 4.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Creme de leite ninho', 'Creme de leite ninho - adicional extra para açaí', 5.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Maracujá polpa', 'Maracujá polpa - adicional extra para açaí', 3.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Morango polpa', 'Morango polpa - adicional extra para açaí', 5.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Salada de frutas', 'Salada de frutas - adicional extra para açaí', 5.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Suflair', 'Suflair - adicional extra para açaí', 5.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Trento', 'Trento - adicional extra para açaí', 4.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Kit Kat', 'Kit Kat - adicional extra para açaí', 4.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Prestígio', 'Prestígio - adicional extra para açaí', 4.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Ovomaltine cremoso', 'Ovomaltine cremoso - adicional extra para açaí', 5.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Creme de amendoim', 'Creme de amendoim - adicional extra para açaí', 5.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Polpa frutas vermelhas', 'Polpa frutas vermelhas - adicional extra para açaí', 4.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true); 