-- 🍦 PRODUTOS FINAIS DA SORVETERIA CONTEINER
-- Execute este script após executar os scripts de estrutura

-- 1. Primeiro, limpar dados existentes
DELETE FROM produto_sabores WHERE produto_id IN (SELECT id FROM produtos WHERE bar_id = (SELECT id FROM bares LIMIT 1));
DELETE FROM produtos WHERE bar_id = (SELECT id FROM bares LIMIT 1);
DELETE FROM categorias WHERE bar_id = (SELECT id FROM bares LIMIT 1);

-- 2. Inserir categorias organizadas
INSERT INTO categorias (nome, descricao, bar_id) VALUES
('Gelatos Container', 'Gelatos especiais da casa', (SELECT id FROM bares LIMIT 1)),
('Copos de Sorvete', 'Copos com diferentes quantidades de bolas', (SELECT id FROM bares LIMIT 1)),
('Cestinhas de Sorvete', 'Cestinhas com diferentes quantidades de bolas', (SELECT id FROM bares LIMIT 1)),
('Cascão e Casquinha', 'Cascão e casquinhas tradicionais', (SELECT id FROM bares LIMIT 1)),
('Milkshakes', 'Milkshakes de diversos tamanhos', (SELECT id FROM bares LIMIT 1)),
('Potes Sorvete', 'Potes com múltiplas bolas', (SELECT id FROM bares LIMIT 1)),
('Taças', 'Taças especiais com coberturas', (SELECT id FROM bares LIMIT 1)),
('Açaí', 'Açaí na tigela e marmita', (SELECT id FROM bares LIMIT 1)),
('Adicionais', 'Adicionais para milkshakes e açaí', (SELECT id FROM bares LIMIT 1)),
('Self-Service', 'Sorvete por quilo', (SELECT id FROM bares LIMIT 1));

-- 3. Inserir produtos principais
INSERT INTO produtos (nome, descricao, preco, categoria_id, bar_id, ativo) VALUES
-- Gelatos Container
('Copo P (01 sabor)', 'Gelato em copo pequeno', 14.00,
 (SELECT id FROM categorias WHERE nome = 'Gelatos Container' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Copo M (02 sabores)', 'Gelato em copo médio', 16.00,
 (SELECT id FROM categorias WHERE nome = 'Gelatos Container' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Copo G (03 sabores)', 'Gelato em copo grande', 19.00,
 (SELECT id FROM categorias WHERE nome = 'Gelatos Container' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Para viagem Pote (1/2 kg)', 'Pote para viagem 1/2 kg', 40.00,
 (SELECT id FROM categorias WHERE nome = 'Gelatos Container' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Para viagem Pote (1kg)', 'Pote para viagem 1kg', 75.00,
 (SELECT id FROM categorias WHERE nome = 'Gelatos Container' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),

-- Copos de Sorvete
('COPO 1 BOLA Simples', 'Copo com 1 bola simples', 6.00,
 (SELECT id FROM categorias WHERE nome = 'Copos de Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('COPO 1 BOLA Recheado', 'Copo com 1 bola recheado', 8.00,
 (SELECT id FROM categorias WHERE nome = 'Copos de Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('COPO 2 BOLAS Simples', 'Copo com 2 bolas simples', 12.00,
 (SELECT id FROM categorias WHERE nome = 'Copos de Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('COPO 2 BOLAS Recheado', 'Copo com 2 bolas recheado', 14.00,
 (SELECT id FROM categorias WHERE nome = 'Copos de Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('COPO 3 BOLAS Simples', 'Copo com 3 bolas simples', 18.00,
 (SELECT id FROM categorias WHERE nome = 'Copos de Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('COPO 3 BOLAS Recheado', 'Copo com 3 bolas recheado', 20.00,
 (SELECT id FROM categorias WHERE nome = 'Copos de Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),

-- Cestinhas de Sorvete
('1 BOLA Simples', 'Cestinha com 1 bola simples', 8.00,
 (SELECT id FROM categorias WHERE nome = 'Cestinhas de Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('1 BOLA Recheada', 'Cestinha com 1 bola recheada', 10.00,
 (SELECT id FROM categorias WHERE nome = 'Cestinhas de Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('2 BOLAS Simples', 'Cestinha com 2 bolas simples', 14.00,
 (SELECT id FROM categorias WHERE nome = 'Cestinhas de Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('2 BOLAS Recheada', 'Cestinha com 2 bolas recheada', 16.00,
 (SELECT id FROM categorias WHERE nome = 'Cestinhas de Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('3 BOLAS Simples', 'Cestinha com 3 bolas simples', 20.00,
 (SELECT id FROM categorias WHERE nome = 'Cestinhas de Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('3 BOLAS Recheada', 'Cestinha com 3 bolas recheada', 22.00,
 (SELECT id FROM categorias WHERE nome = 'Cestinhas de Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('4 BOLAS Simples', 'Cestinha com 4 bolas simples', 26.00,
 (SELECT id FROM categorias WHERE nome = 'Cestinhas de Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('4 BOLAS Recheada', 'Cestinha com 4 bolas recheada', 28.00,
 (SELECT id FROM categorias WHERE nome = 'Cestinhas de Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),

-- Cascão e Casquinha
('Cascão 1 bola', 'Cascão com 1 bola', 8.00,
 (SELECT id FROM categorias WHERE nome = 'Cascão e Casquinha' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Cascão 2 bolas', 'Cascão com 2 bolas', 14.00,
 (SELECT id FROM categorias WHERE nome = 'Cascão e Casquinha' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Casquinha 1 bola', 'Casquinha com 1 bola', 6.00,
 (SELECT id FROM categorias WHERE nome = 'Cascão e Casquinha' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Casquinha 2 bolas', 'Casquinha com 2 bolas', 12.00,
 (SELECT id FROM categorias WHERE nome = 'Cascão e Casquinha' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),

-- Milkshakes
('Milkshake 300ml', 'Milkshake 300ml', 16.00,
 (SELECT id FROM categorias WHERE nome = 'Milkshakes' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Milkshake 400ml', 'Milkshake 400ml', 18.00,
 (SELECT id FROM categorias WHERE nome = 'Milkshakes' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Milkshake 500ml', 'Milkshake 500ml', 21.00,
 (SELECT id FROM categorias WHERE nome = 'Milkshakes' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),

-- Potes Sorvete
('4 bolas', 'Pote com 4 bolas', 24.00,
 (SELECT id FROM categorias WHERE nome = 'Potes Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('5 bolas', 'Pote com 5 bolas', 30.00,
 (SELECT id FROM categorias WHERE nome = 'Potes Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('6 bolas', 'Pote com 6 bolas', 36.00,
 (SELECT id FROM categorias WHERE nome = 'Potes Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('7 bolas', 'Pote com 7 bolas', 42.00,
 (SELECT id FROM categorias WHERE nome = 'Potes Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('8 bolas', 'Pote com 8 bolas', 48.00,
 (SELECT id FROM categorias WHERE nome = 'Potes Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('9 bolas', 'Pote com 9 bolas', 54.90,
 (SELECT id FROM categorias WHERE nome = 'Potes Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('10 bolas', 'Pote com 10 bolas', 60.00,
 (SELECT id FROM categorias WHERE nome = 'Potes Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('12 bolas', 'Pote com 12 bolas', 72.00,
 (SELECT id FROM categorias WHERE nome = 'Potes Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('16 bolas', 'Pote com 16 bolas', 96.00,
 (SELECT id FROM categorias WHERE nome = 'Potes Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('18 bolas', 'Pote com 18 bolas', 108.00,
 (SELECT id FROM categorias WHERE nome = 'Potes Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('20 bolas', 'Pote com 20 bolas', 120.00,
 (SELECT id FROM categorias WHERE nome = 'Potes Sorvete' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),

-- Taças (descrições concisas)
('SUNDAE', '3 sabores, chantilly, cereja, castanha, coberturas', 25.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('VACA PRETA', '2 sabores e coca KS', 20.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('HULA-HULA', '3 sabores, abacaxi, chantilly, castanha, coberturas', 28.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('HULA-HULA TURBO', '5 sabores, abacaxi, chantilly, castanha, coberturas', 35.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('MORANGO SPLIT', '3 sabores, morangos, chantilly, castanha, coberturas', 26.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('BANANA SPLIT', '3 sabores, banana, chantilly, cereja, coberturas', 26.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('COLEGIAL', '1 sabor, chantilly, cereja, castanha, coberturas', 13.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('MILK SHAKE GOURMET', '2 sabores, creme de avelã, chantilly, coberturas', 20.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('TAÇA OVOMALTINE', '2 sabores, brigadeiro, ovomaltine, chantilly', 35.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('TAÇA SONHO DE VALSA', '2 sabores, brigadeiro, sonho de valsa, chantilly', 35.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('TAÇA FRAGOLA', '2 sabores, morangos, chantilly, suspiros', 28.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('TAÇA DESEJO', '2 sabores, morangos, creme de avelã, castanha', 30.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Taça com creme de ninho e negresco', '2 sabores, creme de ninho, negresco, chantilly', 32.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Taça com ouro branco', '2 sabores, brigadeiro, ouro branco, chantilly', 32.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Taça com morangos', '2 sabores, brigadeiro, morangos, chantilly', 38.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Taça com paçoca', '2 sabores, brigadeiro, paçoca, creme de amendoim', 35.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Taça com pistache', '2 sabores, creme de pistache, castanhas, chantilly', 42.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Taça Salada de Frutas', '1 sabor, salada de frutas, groselha, chantilly', 22.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Taça com creme de ninho e leite em pó', '2 sabores, creme de ninho, leite em pó, chantilly', 35.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Taça com granulé', '2 sabores, brigadeiro, granulé, cereja, chantilly', 35.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Taça Festa', '2 sabores, brigadeiro, granulado colorido, confetes', 22.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Taça Doce de Leite com Banana', '2 sabores, doce de leite, creme de ninho, banana', 35.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Taça Goma Fini', '3 sabores, goma fini, confetes, granulado colorido', 25.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Taça com Brownie', '1 sabor, brownie, creme de avelã, morango, chantilly', 25.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Taça com Bolo Petit', '1 sabor, bolo petit, morango, chantilly', 24.00,
 (SELECT id FROM categorias WHERE nome = 'Taças' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),

-- Açaí
('Açaí na tigela', 'Serve 1 pessoa, 3 acompanhamentos inclusos', 21.00,
 (SELECT id FROM categorias WHERE nome = 'Açaí' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Marmita de açaí', 'Serve 2 pessoas, 4 acompanhamentos inclusos', 33.00,
 (SELECT id FROM categorias WHERE nome = 'Açaí' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),

-- Adicionais
('Adicional Ovomaltine', 'Adicional de Ovomaltine para milkshakes', 3.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),
('Adicional Chantilly', 'Adicional de Chantilly para milkshakes', 3.00,
 (SELECT id FROM categorias WHERE nome = 'Adicionais' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true),

-- Self-Service
('Self-Service por Kg', 'Sorvete por quilo - escolha os sabores', 0.00,
 (SELECT id FROM categorias WHERE nome = 'Self-Service' LIMIT 1),
 (SELECT id FROM bares LIMIT 1), true);

-- 4. Verificar se tudo foi inserido corretamente
SELECT 
    c.nome as categoria,
    COUNT(p.id) as total_produtos,
    MIN(p.preco) as preco_min,
    MAX(p.preco) as preco_max
FROM categorias c
LEFT JOIN produtos p ON c.id = p.categoria_id
WHERE c.bar_id = (SELECT id FROM bares LIMIT 1)
GROUP BY c.nome, c.id
ORDER BY c.nome; 